### PR TITLE
add alerts to API

### PR DESCRIPTION
**Pull request by mellema**
Hey I'd like to add wunderground alerts to your project. Thanks!

### CODE REVIEW

**Comment by jaxgeller** [comment]
Thanks for the PR, the tests look like theyre failing because the api has been revoked. I'll add that back in in a bit, then work on merging it in.

Thanks!

**Comment by mellema** [comment]
Great! Thanks for the quick reply. 😁

**Comment by jaxgeller** [comment]
Thanks for the PR, merged and pushed up to npm!

**Comment by mellema** [comment]
Sweet! Thanks again.

**Pull request merged**
